development:
  adapter: postgresql
  encoding: unicode
  database: supermanager_development
  pool: 5
  username: root
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: supermanager_test
  pool: 5
  username: root
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: supermanager_production
  pool: 5
  username: root
  password:
